"use client";
import { useState } from "react";
import { DisclaimerModal } from "@/components/DisclaimerModal";

export function TradeRecUpsell() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <div className="border border-bb-amber/50 bg-bb-darkgray p-4 text-center">
        <div className="text-bb-amber text-xs font-bold mb-2">
          🔒 TRADE RECOMMENDATIONS — PRO
        </div>
        <p className="text-bb-white text-xs leading-relaxed mb-3">
          Options structures generated by Claude Sonnet 4. Enter the access
          password to unlock.
        </p>
        <button
          onClick={() => setOpen(true)}
          className="border border-bb-amber text-bb-amber px-3 py-1 text-xs hover:bg-bb-amber/10"
        >
          UNLOCK
        </button>
      </div>
      {open && <DisclaimerModal forceMode="upgrade-prompt" onClose={() => setOpen(false)} />}
    </>
  );
}
